# Generated by Django 2.2.5 on 2019-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
