# Generated by Django 2.2.5 on 2019-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190912_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
