# Generated by Django 2.2.5 on 2019-09-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Address line 2'),
        ),
    ]
